# Generated by Django 4.2.4 on 2023-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_applyform_previous_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='years_of_experience',
            field=models.IntegerField(default='', null=True),
        ),
    ]
