# Generated by Django 4.2.4 on 2023-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_applyform_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=100),
        ),
    ]
